# Generated by Django 2.0.4 on 2018-05-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='field', to='scheduler.Field'),
        ),
    ]
