# Generated by Django 2.0.4 on 2018-05-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20180530_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
